document.writeln("<div class=\'header\'>");
document.writeln("    <div class=\'left\'>");
document.writeln("        <img id=\'zhite\' src=\'/zhite.png\' alt=\'zhite\' height=\'100px\'>");
document.writeln("    </div>");
document.writeln("    <div class=\'title\'>");
document.writeln("        <h1 id=\'titletext\' color=\'white\'>跨越人<br>KUAYUEREN</h1>");
document.writeln("    </div>");
document.writeln("    <div class=\'info\' align=\'right\'>");
document.writeln("        <p>");
document.writeln("            站长：John Franklin <br> <a href=\'https://GitHub.com/JohnFranklin523\' style=\'color: white\' target=\'_blank\'> GitHub </a> <br> Justice523@outlook.com <br> CC-BY v3.0 unless stated");
document.writeln("        </p>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<ul>");
document.writeln("    <li>");
document.writeln("        <a class=\'active\' href=\'/index.html\'>首页<br>Index</a>");
document.writeln("    </li>");
document.writeln("    <li>");
document.writeln("        <a class=\'active\' href=\'/cns/index.html\'>OpenTTD 中国包指南<br>China Set Guide</a>");
document.writeln("    </li>");
document.writeln("    <li>");
document.writeln("        <a class=\'active\' href=\'/jfserver/index.html\'>OpenTTD<br>JFServer</a>");
document.writeln("    </li>");
document.writeln("    <li>");
document.writeln("        <a class=\'active\' href=\'/webchat/index.html\'>IRC 聊天室<br>IRC WebChat</a>");
document.writeln("    </li>");
document.writeln("    <li>");
document.writeln("        <a class=\'active\' href=\'/project/index.html\'>资料室与存档项目<br>Projects & Archives</a>");
document.writeln("    </li>");
document.writeln("    <li>");
document.writeln("        <a class=\'active\' href=\'/journal/index.html\'>铁路与旅行纪实<br>Railway & Journal</a>");
document.writeln("    </li>");
document.writeln("    <li>");
document.writeln("        <a class=\'active\' href=\'/about/index.html\'>关于<br>About</a>");
document.writeln("    </li>");
document.writeln("    <li>");
document.writeln("        <a class=\'active\' href=\'/links/index.html\'>链接集<br>Links</a>");
document.writeln("    </li>");
document.writeln("</ul>");